## Review template file for Quarterly Refresh MinimalVM test runs on OSD

Instance = "https://openqa.suse.de" # openQA instance to query
RabbitMQ = "amqps://suse:suse@rabbit.suse.de" # RabbitMQ instance to query
RabbitMQTopic = "suse.openqa.job.done" # RabbitMQ topic to query
HideStatus = [
  "scheduled",
  "passed",
  "softfailed",
  "cancelled",
  "skipped",
  "running",
  "uploading",
  "parallel_failed",
  "reviewed",
  "user_cancelled",
] # Hide jobs in defined states
RefreshInterval = 60 # Refresh from API once every minute
MaxJobs = 20 # Max. job per group to display
GroupBy = "groups" # Group by defined groups ("none" or "groups")
RequestJobLimit = 100 # Query up to 100 jobs per http request

## Quarterly Refresh MinimalVM ##################################################

[[Groups]]
Name = "Maintenance - QR - SLE16.0-MinimalVM"
Params = { groupid = "703" }

[[Groups]]
Name = "Maintenance - QR - 15SP7 MinimalVM"
Params = { groupid = "450" }

[[Groups]]
Name = "Maintenance - QR - 15SP6 MinimalVM"
Params = { groupid = "581" }

[[Groups]]
Name = "Maintenance - QR - 15SP5 MinimalVM"
Params = { groupid = "374" }
