## Review template file for PublicCloud test runs on OSD

Instance = "https://openqa.suse.de" # openQA instance to query
RabbitMQ = "amqps://suse:suse@rabbit.suse.de" # RabbitMQ instance to query
RabbitMQTopic = "suse.openqa.job.done" # RabbitMQ topic to query
HideStatus = [
  "scheduled",
  "passed",
  "softfailed",
  "cancelled",
  "skipped",
  "running",
  "uploading",
  "parallel_failed",
  "reviewed",
  "user_cancelled",
] # Hide jobs in defined states
Notify = false # No notifications by default
RefreshInterval = 60 # Refresh from API once every minute
MaxJobs = 20 # Max. job per group to display
GroupBy = "groups" # Group by defined groups ("none" or "groups")
DefaultParams = { distri = "sle" } # Set of default parameters
RequestJobLimit = 100 # Query up to 100 jobs per http request

## Latest images ###############################################################

[[Groups]]
Name = "PublicCloud Latest - Azure"
Params = { groupid = "219" }
MaxLifetime = 86400
[[Groups]]
Name = "PublicCloud Latest - EC2"
Params = { groupid = "274" }
MaxLifetime = 86400
[[Groups]]
Name = "PublicCloud Latest - GCE"
Params = { groupid = "275" }
MaxLifetime = 86400

## Maintenance images ##########################################################

[[Groups]]
Name = "PublicCloud Application"
Params = { groupid = "688" }
MaxLifetime = 86400

[[Groups]]
Name = "PublicCloud Mainteanance Images - Azure"
Params = { groupid = "463" }
MaxLifetime = 86400
[[Groups]]
Name = "PublicCloud Mainteanance Images - EC2"
Params = { groupid = "464" }
MaxLifetime = 86400
[[Groups]]
Name = "PublicCloud Mainteanance Images - GCE"
Params = { groupid = "465" }
MaxLifetime = 86400
[[Groups]]
Name = "PublicCloud Mainteanance Images - SAP"
Params = { groupid = "640" }
MaxLifetime = 86400
[[Groups]]
Name = "PublicCloud Mainteanance Images - SLEM"
Params = { groupid = "653" }
MaxLifetime = 86400

[[Groups]]
Name = "LTP Stable"
Params = { groupid = "659" }
MaxLifetime = 86400


# Create openQA helper instance disk image

[[Groups]]
Name = "Create publiccloud-tools HDD"
Params = { groupid = "276", build = "" }
MaxLifetime = 86400
