." Manpage for openqa-mon
." Contact felix.niederwanger@suse.de to correct errors and/or typos.
.TH openqa-mon 8 "23 Apr 2020" "1.0" "openqa-mon man page"
.SH NAME
openqa-mon - CLI client for monitoring status of openQA jobs
.SH SYNOPSIS
openqa-mon [OPTIONS] REMOTE [JOBS]
.SH DESCRIPTION
openqa-mon is a command line tool for monitoring and live monitoring of jobs on
an openQA instance. The tool periodically queries one or multiple instances
and gives or an overview of the currently running jobs or monitors a set of
given job IDs.
.SH OPTIONS
.TP
.B -h|--help
Print help message

.TP
.B -j|--jobs JOBS
Monitor given job IDs instead of overview on the REMOTE instance.
Supported input is a single job ID, multiple comma-separated job IDs or a job ID range (See examples).
The -j parameter can be omitted, openqa-mon detects an integer, set of interger or integer range automatically and treats them as job IDs

.TP
.B -c|--continuous SECONDS
Enable live monitor and refresh at the given SECONDS intervals

.SH EXAMPLES

.TP
.B openqa-mon https://openqa.opensuse.org
.TP
.PP
List current overview of the instance at https://openqa.opensuse.org

.TP
.nf
.B openqa-mon https://openqa.opensuse.org -j 42
.TP
.PP
List the status of the job 42 on https://openqa.opensuse.org

.TP
.nf
.B openqa-mon https://openqa.opensuse.org -j 42..45
.TP
.PP
List the status of the jobs 42,43,44 and 45 from https://openqa.opensuse.org


.TP
.nf
.B openqa-mon https://openqa.opensuse.org 42 1335..1339
.TP
.PP
List the status of the jobs 42 and the jobs from 1335 to 1339. The -j parameter can be omitted
openqa-mon detects integers, sets of integers and integer ranges and treats them as job IDs.

.TP
.nf
.B openqa-mon -c 5 https://openqa.opensuse.org 42,1335..1339
.TP
.PP
Continuously monitor the jobs 42 and the jobs from 1335 to 1339. Refresh every 5 seconds


.SH COPYRIGHT
.PP
Copyright (C) 2020 SUSE LLC

.SH CREDITS
.PP
Creator: Felix Niederwanger <felix.niederwanger@suse.de>

Thanks for the constructive feedback to (in no particular order)

- Christian Dywan - Pavel Dostal - Oliver Kurz -

This tool has been created to help me and my colleagues work better with openQA.


.SH
.PP
https://github.com/grisu48/openqa-mon openqa-mon(8)
